### ISSUE TITLE
The process [Deleting timestamp] block sync for ~10 minutes

### ISSUE THREAD

**Issue by UNIPOOL** [turtlecoin/turtlecoin#132]
Hi I want to make a request for know if it's possible to make another thread for this process of deleting timestamp in parallel. 

This process come after some days or some hours and he is repeated a few times and **stuck for the same block height 190244**. 
This process can block the sync for 10 minutes and after, the sync going fast like before when the process don't happen.

I hope the team can make a system for processing it in parallel.

Screenshot:
![unknown](https://user-images.githubusercontent.com/37265696/38171575-815d0f4c-359c-11e8-8ddd-8ecf686862f4.png)
![unknown 1](https://user-images.githubusercontent.com/37265696/38171574-8142a800-359c-11e8-9c78-3ebc0a5e2653.png)

Thank you very much.

**Comment by ZedPea** [comment]
The current daemon is terribly threaded, and when I tried to do some processing in parallel at least on the wallet, it ended up crashing instantly on Windows due to the dispatcher only supporting one thread.

Of course pool owners aren't on Windows, but my meaning is that the codebase is not very friendly to multi-threading at all. A work around may be possible from someone smarter than me, but this is part of the reason a fresh codebase would be a good idea.

**Comment by RocksteadyTC** [comment]
Essayer avec le nouveau 0.4.3 qui crorige quelques issues. Si les problemes persister, dit nous, ets nous ouvrions lissue encors. Merci! Bon Chance :)
Please upgrade to 0.4.3 and reopen the issue if the problem persists. Thank you.
