### ISSUE TITLE
Dust outputs generated by standard transactions

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtlecoin#220]
As we were talking about in dev_general a bit ago, we see dust outputs accumulating in wallets, and these can't be sent without using 0 mixin, which is not beneficial to the network privacy as a whole.

The dust threshold is currently set to 0.1 TRTL. I was under the impression that only micro transactions (i.e, manually sending) could cause these outputs, however upon further inspection, we see standard large transactions potentially giving outputs below this amount.

For example, this miner transaction http://turtle-block.com/?hash=c3051a2fb1ba8d0a153ca55d83c35047519d9bd6a5841d71f8ecb7424842bf03#blockchain_transaction gives an output of 0.06 TRTL, which is now unspendable without using 0 mixin.

Two things come to mind here:

1) Can we lower the dust threshold? This could be worth trying out on testnet or digging into the code for.
2) Can we change how the outputs are generated to not generated dust?

**Comment by RocksteadyTC** [comment]
1) I think this would be an easy one to test. I don't see too many downsides other than potentially enabling bloated small transactions down the road. However, unless those tiny transactions impact the flow of the network, I'm not sure it warrants us intervening.

2) We should instead consider RingCT, which makes the output matching inconsequential, since amounts become obfuscated. https://monero.stackexchange.com/questions/1731/selection-of-outputs-with-ringct

**Comment by ZedPea** [comment]
Was checking out karbowanec's code, and they have changed DEFAULT_DUST_THRESHOLD to 0.
https://github.com/seredat/karbowanec/commit/2bb5330ee6b5ea2b6706b1b7eb6d6a0ec12d4f15

**Comment by RocksteadyTC** [comment]
This change has been merged in to main. Closing and can reopen if problems occur.
