### ISSUE TITLE
at wallet generation, user is asked to backup mnemonic seed + keys

### ISSUE THREAD

**Issue by woodyjon** [turtlecoin/turtlecoin#252]
When generating a wallet with simplewallet, the user is presented with the 2 private keys and the mnemonic seed, and asked to backup all of those.
I believe only the seed should be presented and required to backup, as it is a representation of the private spend key, and the private view key is directly derived from the private spend key. The seed is enough and it would simplify the user experience.

**Comment by RocksteadyTC** [comment]
What if instead of removing that entirely, we instead mute it from the creation message and allow the user to `export_seed` as well as `export_keys`

**Comment by darutse** [comment]
simplewallet is a command line tool, therefore user should be somewhat familiar with how these wallets work. I personally always ignore the seed and care only about private keys. To be 100% sure of restoring from seed you would need that particular wallet, some wallets may not accept seed, or limit you in other ways.
Private keys on the other hand are always prefered because you can restore from them no matter what, even if the algorithm of generating the seed would change in 10 years from now.. or if that wallet no longer be developed or something like that.
Of course seed is easier to write or remember, so it should probably also be present.
But I'm against hiding the private keys, at least in simplewallet, I also don't see the reason to make two commands for basically the same action.
Maybe the better solution is to briefly explain in export_keys that you can restore from either of these (keys or seed) and that you don't have to backup all of them (if for example you ouse paper to store your keys)

**Comment by woodyjon** [comment]
The seed is the private spend key, just wrote in another way. And in the new simplewallet, the private view key is just a hash of the private spend key. So backing all those 3 is useless.
simplewallet is indeed a command line tool, so not used by anybody for sure. So I think there is no harm to displaying the 3. But I think at least it should be specified than you just need to backup the seed. Command line tools are used by geeks, but not all of them are crypto specialists. If you present the 3, most of the people do not know that the seed is enough.
I would agree with rock's proposal. If you want your key, you can ask them. But if you don't ask them specifically, there is no reason to show it to you, you don't need them.

The purpose of the 25 words seed is that you can write them down on a piece of paper without having to make copy and paste and to save them electronically. When you backup the 2 other keys, you have to make a copy and paste, as it is tedious to write down and easy to make typos. You therefore undermine your security, as you are almost forced to keep a digital copy.

**Comment by ZedPea** [comment]
Well, there is the issue that currently not many wallets can import via seeds. If they all offered seed import then I would agree, but then if a user wants to user a GUI wallet, they either have to redig out their cli wallet to export their keys, or enter their keys in turtlecoin.lol/wallet (how would they know to do this?) or come ask for help in discord.

I think we should could keep it as easy as possible until all GUI's support mnemonics.

**Comment by SoreGums** [comment]
is supporting mnemonics a matter of updating walletd and all guis then use the walletd api method - or does each gui need to figure out how to go from mnemonic to what walletd can disgest?

**Comment by ZedPea** [comment]
Walletd already supports mnemonics - I forget the link for the API docs but there's a getMnemonicSeed() RPC method in there - however if a user has made a subaddress they won't have a mnemonic seed, or if they have an old wallet (pre mnemonics), they can't get a mnemonic seed.

**Comment by SoreGums** [comment]
subaddresses are where things get icky I think.

in one of the windows gui wallets creating sub addresses was very simple, however need

**Comment by woodyjon** [comment]
In Nest, import from seed is coming soon.

For our discussion, I would say there are 2 main cases:

1. wallet where private view key is hash of private spend key
2. wallet where private view key is not hash of private spend key: old wallet or wallet with subwallets

In 1st case, user should be requested to backup the seed. In 2nd case, user should be requested to backup the private keys.

But indeed, better to wait for all or most of the GUIs to implement import from seed.

BTW, how are constructed the keys for subwallets?
