### ISSUE TITLE
Trying to set up wallet.  Got this error

### ISSUE THREAD

**Issue by coinnut** [turtlecoin/turtlecoin#31]
![turtle error 001](https://user-images.githubusercontent.com/36139115/35782466-8a973b5c-09c6-11e8-9cd4-0dceba2bbc4e.jpg)

**Comment by RocksteadyTC** [comment]
Hmmm. That's a new one to me. Does the issue persist after relaunching without typing commands? Was the sync process interrupted in simplewallet? There's a small re-sync done in simplewallet when launching it where it checks out the blocks from where it left off, and since it isn't giving a visual indicator sometimes that the refresh is happening, people end up CTRL_C'ing it or typing commands. Let us know some more details and we'll get you taken care of.

**Comment by coinnut** [comment]
Thanks for the advice.  I tried again and it worked.

**Comment by RocksteadyTC** [comment]
Sweet :)
