### ISSUE TITLE
export_keys command leaves view and spend keys in cleartext in simplewallet log

### ISSUE THREAD

**Issue by nnamon** [turtlecoin/turtlecoin#37]

**Comment by nnamon** [comment]
Assigned to @editfmah

**Comment by editfmah** [comment]
@RocksteadyTC, are you dealing with this then?

I initially looked to extent the log level to add a "PRIVATE", level but it turns out there are just loads of bugs where the global level is already elevated and the logs marked as private still get logged out.

So the PR just has a plain and simple "cout" in it.  But actually we want to change all the log levels to be security levels and bitwise OP's.  Then use them throughout to make sure you have the right privileges to see anything/execute commands/request API data etc..

**Comment by RocksteadyTC** [comment]
I think that was a kneejerk assign

**Comment by RocksteadyTC** [comment]
@editfmah please accept invite to this repo.

**Comment by SoreGums** [comment]
so the issue seems fixed, lets close this one
https://github.com/turtlecoin/turtlecoin/pull/40

then open a new one for the feature request of fixing up the logging situation for realz - nice work Adrian
