### ISSUE TITLE
Zedwallet: Request node fee of prior transaction be stored locally in the wallet file for better reporting

### ISSUE THREAD

**Issue by gobblegames** [turtlecoin/turtlecoin#498]
### System Information

**Operating System**: Win 10 Professional
**OS Version**: 1803
**CPU Make, Model, & Speed**: Intel i7-6700 @ 3.40GHZ
**Amount of RAM**: 16.00 GB DDR4 2133mhz
**Hard Drive Type**: SSD
**Hard Drive Size**: 120GB
**Volume Type**: NTFS

### TurtleCoin Build Information

**Version:** 0.8.3
**Binary Source:** https://github.com/turtlecoin/turtlecoin/releases/tag/v0.8.3
**If self compiled, please provide all the build commands you used**

```I used the already built binaries.```

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:

```
```

### Issue Report

**Binary Reported:** Zedwallet

#### Expected Behavior

Outgoing transfer:
Hash: <hash>
Block height: <blockheight>
Timestamp: <datetime>
Spent: <amount> TRTL
Fee: 250.10 TRTL
Total Spent: <amount> TRTL
Payment ID: <paymentid>

OR

Outgoing transfer:
Hash: <hash>
Block height: <blockheight>
Timestamp: <datetime>
Spent: <amount> TRTL
Fee: 0.10 TRTL
Node Fee: 250.00 TRTL
Total Spent: <amount> TRTL
Payment ID: <paymentid>

#### Current Behavior

Node fee is not included in the fees at all.

Outgoing transfer:
Hash: <hash>
Block height: <blockheight>
Timestamp: <datetime>
Spent: <amount> TRTL
Fee: 0.10 TRTL
Total Spent: <amount> TRTL
Payment ID: <paymentid>

##### Screen Shots

![image](https://user-images.githubusercontent.com/42309092/45596591-6fe7dc80-ba01-11e8-9ece-f08f41a1c157.png)

#### Steps to Reproduce

1. Connect to remote node
2. Log in to wallet
3. type outgoing_transfers or 17
4. No node fee is included in the Fee (or as a separate listed item). This info is needed for those who can claim fees as an expense.

#### Possible Solution

Add a Node Fee field to the transaction, or like this: Fee: 0.10 TRTL + 250.00 TRTL (Node Fee)

**Comment by zpalmtree** [comment]
I don't believe this is possible unfortunately. If we check out our [transaction struct](https://github.com/turtlecoin/turtlecoin/blob/development/include/IWallet.h#L80), we see we've got a member `totalAmount`, and `fee`.

Whilst we send to two separate destinations when forming our transaction, when this turns into a binary transaction and gets included on the chain, it's just a combination of inputs, to outputs.

When we read it back from the chain, for example if we are importing our wallet, all we get is this totalAmount, and fee. We can't include the node fee in the fee field, because the fee goes to the miner, and we can't work out that 250 of the total amount went to a certain destination, because all we have is a bunch of key images.

It's *possible* with some heavy modification we could potentially figure out if a certain key image went to a certain address, but I think it would require enumerating all our stored key images and encrypting them with the addresses we sent to, which we can't get off the chain data, only externally.

We could store this in the wallet file, by adding a separate field, however, it would only be stored in that wallet file, and if you re-imported your wallet, you would no longer be able to retrieve that data.

**Comment by brandonlehmann** [comment]
Good points. However any tracking of where the key image went to is impossible after the fact as that defeats the privacy and wouldn’t work because of the private key pair. You can’t decrypt the image with the key you signed it with. Only the receiver can. I think this is stuck in the main transfer amount.

**Comment by zpalmtree** [comment]
For sure, I more meant something like, given my key image inputs, encrypt with node public address, and see if it matches the key image in this transaction. That still might not be possible, though.

**Comment by brandonlehmann** [comment]
That sounds slow and painful. 

Have to have a think. To the network and the software it’s not a fee. It’s just another voluntary transfer.

**Comment by zpalmtree** [comment]
Aye, wasn't suggesting we do it, it's unfeasible. I don't think it's possible legitimately without significant work.

**Comment by gobblegames** [comment]
I'm satisfied with these responses that this is no longer a bug report but rather a feature request.
I believe the best way would be through a local wallet file rather than on-chain data if it means impacting privacy (not intended). Something to think about.

**Comment by brandonlehmann** [comment]
Changed to enhancement.

**Comment by brandonlehmann** [comment]
Moved to https://github.com/turtlecoin/meta/issues/125
