### ISSUE TITLE
how it works ?

### ISSUE THREAD

**Issue by JOXW** [turtlecoin/turtlecoin#737]
The Blockchain ist very interesting, and turtlecoin is awesome !
I love to try things, and the blockchain technology

how important are nodes and seedworks when you need to change somewhat in the code ?

what happens when the developer wants to change the code and the nodes(daemons) continue to run and form the longest chain?

How can you prevent this as developer ?

if seed nodes are turned off, will the chain continue to grow?

**Comment by SoreGums** [comment]
> how important are nodes and seedworks when you need to change somewhat in the code ?

Question not clear. Here are some stabs in the dark, does breaking the software break the network? yes. All nodes are equal, seednodes are nodes in the config that get conntacted first to connect with other nodes. All nodes need to be running the same consensus rules, else they won't be able to talk to each well. All nodes should run the same software,when making updates give people time to update otherwise they won't and the new changes won't happen.

> what happens when the developer wants to change the code and the nodes(daemons) continue to run and form the longest chain?

There will be two chains, one with new software and changes, and one with old software and no changes. see Bitcoin, Bitcoin Cash, Bitcoin SV or Ethereum, Ethereum Classic, etc

> How can you prevent this as developer ?

You can't technically, you can through a community effort, TurtleCoin community is strong so we've been OK with updates so far.

> if seed nodes are turned off, will the chain continue to grow?

if nodes can talk to each other, then yes, chain will keep growing longer. Anyone can tell anyone an IP of a node and connect.

**Comment by SoreGums** [comment]
also join us in the chat room on Discord :)

http://chat.turtlecoin.lo
