### ISSUE TITLE
How about upgrading PoW algorithm?

### ISSUE THREAD

**Issue by extenami** [turtlecoin/turtlecoin#750]
How about upgrading PoW algorithm?

Now turtlecoin works on CN-Turtle algorithm (a descendant of CNv8/cryptonight variant 2 which is now the main monero algorithm). 
As everyone knows monero has been attacked by ASICs in the mid-January. Apparently now there are about 5000 ASICs with a summury hashrate of more than 600 mhs. 
That's why monero's hardfork for CryptonightR/cryptonight variant 4 is planned for 9 March.
We all remember the story of the previous monero's hardfork (15 October) when lots of CNv7 ASICs moved to turtlecoin network and occupied it for two months. 
I believe that no one want this shit to repeat. (how about extra 600+ mhs hashrate?)

I come up with the idea of updating CN-Turtle algo from CNv8/cryptonight variant 2 to CryptonightR/cryptonight variant 4 with related CN-Turtle algo specificities. 
Hardfork with those changes is better to happen ASAP (experience shows that ASICs appear in a month or two after monero's fork), but there's a need in time 
to update users, miners and exchangers software. In my opinion the best time is the beginning of April.

**Comment by brandonlehmann** [comment]
We are already testing a new hashing algorithm (and have been since before the most recent fork). It does not follow in the steps of Monero and deviates greatly from CryptoNight in general. 

Please see https://github.com/turtlecoin/turtlecoin/issues/716 where we solicited and collected base performance results. Also check out https://github.com/turtlecoin/meta/issues/74
