### ISSUE TITLE
simplewallet not accepting password

### ISSUE THREAD

**Issue by Kiberia** [turtlecoin/turtlecoin#77]
I have GUI and CLI version of wallet.
In CLI, i launch blockchain demon, wait for synchronization. When I'm trying to enter my password, it says password is incorrect.
GUI client works with same password as intended. I've tried at least 10 times in each wallets,  and everytime CLI says it's wrong, and GUI accepts it. I doubt my muscle memory can fail that particular.

Anyone else experiencing same problem?

2018-Feb-20 12:33:22.312497 ERROR   Error: failed to load wallet: can't load wallet file 'xxx.wallet', check password
2018-Feb-20 12:33:22.315497 ERROR   Failed to initialize wallet

**Comment by DuyQuang06** [comment]
You can open a CLI with the GUI, but you can't open a GUI wallet with the CLI.
It make wrong password issue.

**Comment by Kiberia** [comment]
I didn't fully understand your comment, but I'm not trying to open them simultaneously, if that's what you mean

**Comment by Kiberia** [comment]
I'll check specifically later

**Comment by ZedPea** [comment]
Once you have opened a .wallet file with the GUI, it becomes unopenable with the CLI. This is because the GUI takes the CLI wallet format, and converts it to a different format. This format cannot be opened by the CLI, only the GUI. If you want to use the CLI version of the wallet, open up your wallet in the GUI, go to the keys tab, and export your keys.

You can then use simplewallet, and reimport your wallet by pressing `i`. Give this wallet a new, different name (maybe `cli-wallet.bin`), and a password, then enter the keys you previously exported. You will now have one copy of the wallet to use with the GUI, and another for the CLI.

**Comment by Kiberia** [comment]
Thanks! I was thinking something similar, just wanted to make sure.
