### ISSUE TITLE
Cant Create Directory

### ISSUE THREAD

**Issue by tgwaste** [turtlecoin/turtlecoin#875]
Please fix this:
2019-Sep-04 09:49:47.228659 ERROR   Exception: Can't create directory: /root/.TurtleCoin

```
# ls -la /root/.TurtleCoin
lrwxrwxrwx 1 root root 31 Sep  4 09:49 /root/.TurtleCoin -> /archive/blockchains/TurtleCoin
```

Maybe its due to the symlink but this worked perfectly before v0.18.1.1291.

**Comment by brandonlehmann** [comment]
Use the `--data-dir` argument as designed and documented in `--help`

`./TurtleCoind --data-dir /archive/blockchains/TurtleCoin`

**Comment by tgwaste** [comment]
Why has this been closed?  This is a bug.  It should read the default directory even if its symlinked like it has in the past.  Using --data-dir is a work-around not a bug fix.

**Comment by 0des** [comment]
`--data-dir` is the suggested method, rather than symlink. Issue items to accommodate needs that are outside of the normal operating procedures should be filed as feature requests.

**Comment by crappyrules** [comment]
@tgwaste iT's A dOeRs MaRkEt  It's open source code so you're more than welcome to fork it and fix it yourself.  there are literally thousands of shitcoins forked from this and you appear to be the only one having difficulty using the --data-dir flag.

You could also pay a bounty in trtl if you really have a hardon for something so small and insignificant.  Which is why your issue got tossed into the trash.

**Comment by tgwaste** [comment]
These shit practices tell me all I need to know about the coin.  Thanks.
